[".emacs.d"]
    type = "git-repo"
    url = "https://github.com/syl20bnr/spacemacs.git"
    refreshPeriod = "168h"

["zsh-defer"]
    type = "git-repo"
    url = "https://github.com/romkatv/zsh-defer.git"
    refreshPeriod = "168h"
    
[".vim/bundle/Vundle.vim"]
    type = "git-repo"
    url = "https://github.com/VundleVim/Vundle.vim.git"
    refreshPeriod = "168h"
